-- Seu Food: fundação multiempresa.
-- Execute este arquivo uma única vez no SQL Editor depois das migrações anteriores.
-- O catálogo atual é preservado como a loja de demonstração.

create extension if not exists pgcrypto;

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  status text not null default 'active' check (status in ('active','suspended','archived')),
  storefront_enabled boolean not null default true,
  is_demo boolean not null default false,
  plan_name text,
  access_expires_at timestamptz,
  max_products integer check (max_products is null or max_products >= 0),
  max_orders_month integer check (max_orders_month is null or max_orders_month >= 0),
  max_storage_mb integer check (max_storage_mb is null or max_storage_mb >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.store_members (
  store_id uuid not null references public.stores(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'owner' check (role in ('owner','manager','staff')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (store_id, user_id)
);

create table if not exists public.store_domains (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  hostname text not null unique,
  kind text not null default 'custom' check (kind in ('subdomain','custom')),
  status text not null default 'pending' check (status in ('pending','active','error','disabled')),
  is_primary boolean not null default false,
  verification_token text not null default encode(gen_random_bytes(18), 'hex'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_pages (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  slug text not null check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null,
  content jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, slug)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  store_id uuid references public.stores(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.stores (
  id, name, slug, status, storefront_enabled, is_demo,
  plan_name, access_expires_at, max_products, max_orders_month, max_storage_mb
)
values (
  '00000000-0000-0000-0000-000000000001',
  'Seu Delivery - Demonstração',
  'demonstracao',
  'active',
  true,
  true,
  null, null, null, null, null
)
on conflict (id) do update set
  is_demo = true,
  updated_at = now();

-- Preserva o catálogo, pedidos e integrações existentes dentro da demonstração.
alter table public.catalogs add column if not exists store_id uuid;
update public.catalogs
set store_id = '00000000-0000-0000-0000-000000000001'
where store_id is null;
alter table public.catalogs alter column store_id set not null;
alter table public.catalogs drop constraint if exists catalogs_pkey;
alter table public.catalogs
  add constraint catalogs_pkey primary key (store_id, id);
alter table public.catalogs drop constraint if exists catalogs_store_id_fkey;
alter table public.catalogs
  add constraint catalogs_store_id_fkey foreign key (store_id) references public.stores(id) on delete cascade;

alter table public.orders add column if not exists store_id uuid;
update public.orders
set store_id = '00000000-0000-0000-0000-000000000001'
where store_id is null;
alter table public.orders alter column store_id set not null;
alter table public.orders drop constraint if exists orders_store_id_fkey;
alter table public.orders
  add constraint orders_store_id_fkey foreign key (store_id) references public.stores(id) on delete restrict;
alter table public.orders drop constraint if exists orders_payment_status_check;
alter table public.orders
  add constraint orders_payment_status_check check (payment_status in ('pendente','pago','estornado','recusado'));

alter table public.private_settings add column if not exists store_id uuid;
update public.private_settings
set store_id = '00000000-0000-0000-0000-000000000001'
where store_id is null;
alter table public.private_settings alter column store_id set not null;
alter table public.private_settings drop constraint if exists private_settings_pkey;
alter table public.private_settings
  add constraint private_settings_pkey primary key (store_id, id);
alter table public.private_settings drop constraint if exists private_settings_store_id_fkey;
alter table public.private_settings
  add constraint private_settings_store_id_fkey foreign key (store_id) references public.stores(id) on delete cascade;

alter table public.order_webhook_events add column if not exists store_id uuid;
update public.order_webhook_events as event
set store_id = orders.store_id
from public.orders as orders
where event.order_id = orders.id and event.store_id is null;
alter table public.order_webhook_events alter column store_id set not null;
alter table public.order_webhook_events drop constraint if exists order_webhook_events_store_id_fkey;
alter table public.order_webhook_events
  add constraint order_webhook_events_store_id_fkey foreign key (store_id) references public.stores(id) on delete cascade;

create index if not exists catalogs_store_idx on public.catalogs (store_id);
create index if not exists orders_store_created_idx on public.orders (store_id, created_at desc);
create index if not exists orders_store_status_idx on public.orders (store_id, status);
create index if not exists private_settings_store_idx on public.private_settings (store_id);
create index if not exists webhook_events_store_idx on public.order_webhook_events (store_id, created_at desc);
create index if not exists store_members_user_idx on public.store_members (user_id, active);
create index if not exists store_domains_store_idx on public.store_domains (store_id, status);

create or replace function public.is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.platform_admins
    where user_id = (select auth.uid())
  );
$$;

create or replace function public.has_store_access(target_store_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_platform_admin() or exists (
    select 1
    from public.store_members member
    join public.stores store on store.id = member.store_id
    where member.store_id = target_store_id
      and member.user_id = (select auth.uid())
      and member.active = true
      and store.status = 'active'
  );
$$;

create or replace function public.can_manage_store(target_store_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_platform_admin() or exists (
    select 1
    from public.store_members member
    join public.stores store on store.id = member.store_id
    where member.store_id = target_store_id
      and member.user_id = (select auth.uid())
      and member.active = true
      and member.role in ('owner','manager')
      and store.status = 'active'
  );
$$;

create or replace function public.resolve_public_store(requested_slug text default null, requested_hostname text default null)
returns table (
  id uuid,
  name text,
  slug text,
  is_demo boolean,
  primary_hostname text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    store.id,
    store.name,
    store.slug,
    store.is_demo,
    (
      select domain.hostname
      from public.store_domains domain
      where domain.store_id = store.id
        and domain.status = 'active'
      order by domain.is_primary desc, domain.created_at asc
      limit 1
    ) as primary_hostname
  from public.stores store
  where store.status = 'active'
    and store.storefront_enabled = true
    and (
      (requested_slug is not null and store.slug = lower(trim(requested_slug)))
      or exists (
        select 1 from public.store_domains domain
        where domain.store_id = store.id
          and domain.status = 'active'
          and domain.hostname = lower(trim(requested_hostname))
      )
    )
  limit 1;
$$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists stores_touch_updated_at on public.stores;
create trigger stores_touch_updated_at before update on public.stores
for each row execute function public.touch_updated_at();
drop trigger if exists store_members_touch_updated_at on public.store_members;
create trigger store_members_touch_updated_at before update on public.store_members
for each row execute function public.touch_updated_at();
drop trigger if exists store_domains_touch_updated_at on public.store_domains;
create trigger store_domains_touch_updated_at before update on public.store_domains
for each row execute function public.touch_updated_at();
drop trigger if exists store_pages_touch_updated_at on public.store_pages;
create trigger store_pages_touch_updated_at before update on public.store_pages
for each row execute function public.touch_updated_at();

-- O usuário mais antigo do projeto atual torna-se o administrador central.
-- Como o cadastro público estava desativado, este deve ser o proprietário atual.
insert into public.platform_admins (user_id)
select id from auth.users order by created_at asc limit 1
on conflict (user_id) do nothing;

insert into public.store_members (store_id, user_id, role, active)
select '00000000-0000-0000-0000-000000000001', id, 'owner', true
from auth.users
order by created_at asc
limit 1
on conflict (store_id, user_id) do update set active = true, role = 'owner';

alter table public.stores enable row level security;
alter table public.platform_admins enable row level security;
alter table public.store_members enable row level security;
alter table public.store_domains enable row level security;
alter table public.store_pages enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "catalogo publico pode ler" on public.catalogs;
drop policy if exists "administrador gerencia catalogo" on public.catalogs;
drop policy if exists "cliente cria pedido" on public.orders;
drop policy if exists "administrador le pedidos" on public.orders;
drop policy if exists "administrador atualiza pedidos" on public.orders;
drop policy if exists "administrador exclui pedidos" on public.orders;
drop policy if exists "administrador gerencia configuracoes privadas" on public.private_settings;
drop policy if exists "administrador le historico de webhooks" on public.order_webhook_events;
drop policy if exists "lojas publicas ou autorizadas" on public.stores;
drop policy if exists "administrador central gerencia lojas" on public.stores;
drop policy if exists "administrador central consulta seu acesso" on public.platform_admins;
drop policy if exists "membros consultam vinculos autorizados" on public.store_members;
drop policy if exists "administrador central gerencia membros" on public.store_members;
drop policy if exists "catalogo publico da loja ativa" on public.catalogs;
drop policy if exists "gestor administra catalogo da propria loja" on public.catalogs;
drop policy if exists "cliente cria pedido na loja ativa" on public.orders;
drop policy if exists "gestor le pedidos da propria loja" on public.orders;
drop policy if exists "gestor atualiza pedidos da propria loja" on public.orders;
drop policy if exists "gestor exclui pedidos da propria loja" on public.orders;
drop policy if exists "gestor administra integracoes da propria loja" on public.private_settings;
drop policy if exists "gestor consulta eventos da propria loja" on public.order_webhook_events;
drop policy if exists "dominios ativos sao resolvidos publicamente" on public.store_domains;
drop policy if exists "administrador central gerencia dominios" on public.store_domains;
drop policy if exists "paginas publicas da loja ativa" on public.store_pages;
drop policy if exists "gestor administra paginas da propria loja" on public.store_pages;
drop policy if exists "administrador central consulta auditoria" on public.audit_logs;

-- As imagens novas usam o Worker R2 com autorização por empresa.
-- Remove as permissões antigas e genéricas de escrita no Supabase Storage.
drop policy if exists "administrador envia imagens" on storage.objects;
drop policy if exists "administrador atualiza imagens" on storage.objects;
drop policy if exists "administrador remove imagens" on storage.objects;

create policy "lojas publicas ou autorizadas"
  on public.stores for select
  to anon, authenticated
  using (
    (status = 'active' and storefront_enabled = true)
    or public.has_store_access(id)
    or public.is_platform_admin()
  );

create policy "administrador central gerencia lojas"
  on public.stores for all
  to authenticated
  using (public.is_platform_admin())
  with check (public.is_platform_admin());

create policy "administrador central consulta seu acesso"
  on public.platform_admins for select
  to authenticated
  using (user_id = (select auth.uid()) or public.is_platform_admin());

create policy "membros consultam vinculos autorizados"
  on public.store_members for select
  to authenticated
  using (
    user_id = (select auth.uid())
    or public.can_manage_store(store_id)
    or public.is_platform_admin()
  );

create policy "administrador central gerencia membros"
  on public.store_members for all
  to authenticated
  using (public.is_platform_admin())
  with check (public.is_platform_admin());

create policy "catalogo publico da loja ativa"
  on public.catalogs for select
  to anon, authenticated
  using (
    exists (
      select 1 from public.stores store
      where store.id = catalogs.store_id
        and store.status = 'active'
        and store.storefront_enabled = true
    )
    or public.has_store_access(store_id)
  );

create policy "gestor administra catalogo da propria loja"
  on public.catalogs for all
  to authenticated
  using (public.can_manage_store(store_id))
  with check (public.can_manage_store(store_id));

create policy "cliente cria pedido na loja ativa"
  on public.orders for insert
  to anon, authenticated
  with check (
    status = 'novo'
    and payment_status = 'pendente'
    and exists (
      select 1 from public.stores store
      where store.id = orders.store_id
        and store.status = 'active'
        and store.storefront_enabled = true
    )
  );

create policy "gestor le pedidos da propria loja"
  on public.orders for select
  to authenticated
  using (public.has_store_access(store_id));

create policy "gestor atualiza pedidos da propria loja"
  on public.orders for update
  to authenticated
  using (public.can_manage_store(store_id))
  with check (public.can_manage_store(store_id));

create policy "gestor exclui pedidos da propria loja"
  on public.orders for delete
  to authenticated
  using (public.can_manage_store(store_id));

create policy "gestor administra integracoes da propria loja"
  on public.private_settings for all
  to authenticated
  using (public.can_manage_store(store_id))
  with check (public.can_manage_store(store_id));

create policy "gestor consulta eventos da propria loja"
  on public.order_webhook_events for select
  to authenticated
  using (public.has_store_access(store_id));

create policy "dominios ativos sao resolvidos publicamente"
  on public.store_domains for select
  to anon, authenticated
  using (status = 'active' or public.has_store_access(store_id));

create policy "administrador central gerencia dominios"
  on public.store_domains for all
  to authenticated
  using (public.is_platform_admin())
  with check (public.is_platform_admin());

create policy "paginas publicas da loja ativa"
  on public.store_pages for select
  to anon, authenticated
  using (
    (active = true and exists (
      select 1 from public.stores store
      where store.id = store_pages.store_id
        and store.status = 'active'
        and store.storefront_enabled = true
    ))
    or public.has_store_access(store_id)
  );

create policy "gestor administra paginas da propria loja"
  on public.store_pages for all
  to authenticated
  using (public.can_manage_store(store_id))
  with check (public.can_manage_store(store_id));

create policy "administrador central consulta auditoria"
  on public.audit_logs for select
  to authenticated
  using (public.is_platform_admin());

grant usage on schema public to anon, authenticated;
grant select on public.stores, public.store_domains, public.store_pages to anon, authenticated;
grant select, insert, update, delete on public.stores, public.store_members, public.store_domains, public.store_pages to authenticated;
grant select on public.platform_admins, public.audit_logs to authenticated;
grant insert on public.audit_logs to authenticated;
grant execute on function public.is_platform_admin() to authenticated;
grant execute on function public.has_store_access(uuid) to authenticated;
grant execute on function public.can_manage_store(uuid) to authenticated;
grant execute on function public.resolve_public_store(text, text) to anon, authenticated;

insert into public.audit_logs (actor_id, store_id, action, details)
select
  (select user_id from public.platform_admins order by created_at asc limit 1),
  '00000000-0000-0000-0000-000000000001',
  'multi_tenant_migration',
  '{"source":"existing_catalog","billing_enforcement":false}'::jsonb
where not exists (
  select 1 from public.audit_logs where action = 'multi_tenant_migration'
);
