-- Seu Food: pagamentos por empresa, falhas e funil próprio.
-- Execute depois de 004_multi_tenant.sql no SQL Editor do Supabase.

create extension if not exists supabase_vault with schema vault;

create table if not exists public.payment_provider_configs (
  store_id uuid primary key references public.stores(id) on delete cascade,
  provider text not null default 'mercadopago' check (provider in ('mercadopago')),
  enabled boolean not null default false,
  public_key text not null default '',
  access_token_secret_id uuid,
  webhook_secret_id uuid,
  account_id text not null default '',
  account_email text not null default '',
  live_mode boolean not null default false,
  apple_pay_status text not null default 'provider_required'
    check (apple_pay_status in ('provider_required','domain_required','ready','disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_attempts (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  order_id uuid references public.orders(id) on delete set null,
  order_number text not null default '',
  provider text not null default 'mercadopago',
  payment_method text not null default '',
  status text not null check (status in ('created','pending','approved','rejected','error','refunded')),
  external_reference text not null default '',
  amount numeric(12,2) not null default 0,
  reason_code text not null default '',
  reason_message text not null default '',
  source text not null default 'checkout',
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.store_analytics_events (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  session_id text not null default '',
  event_name text not null check (event_name in (
    'view_item','add_to_cart','begin_checkout','order_created',
    'payment_created','payment_failed','purchase','refund'
  )),
  order_id uuid references public.orders(id) on delete set null,
  value numeric(12,2) not null default 0,
  currency text not null default 'BRL',
  item_count integer not null default 0,
  items jsonb not null default '[]'::jsonb,
  attribution jsonb not null default '{}'::jsonb,
  consent jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists payment_attempts_store_date_idx
  on public.payment_attempts (store_id, occurred_at desc);
create index if not exists payment_attempts_failures_idx
  on public.payment_attempts (occurred_at desc)
  where status in ('rejected','error');
create index if not exists analytics_events_store_date_idx
  on public.store_analytics_events (store_id, created_at desc);
create index if not exists analytics_events_store_name_date_idx
  on public.store_analytics_events (store_id, event_name, created_at desc);

alter table public.payment_provider_configs enable row level security;
alter table public.payment_attempts enable row level security;
alter table public.store_analytics_events enable row level security;

drop policy if exists "gestores consultam tentativas de pagamento" on public.payment_attempts;
create policy "gestores consultam tentativas de pagamento"
on public.payment_attempts for select to authenticated
using (public.has_store_access(store_id));

drop policy if exists "gestores consultam funil da empresa" on public.store_analytics_events;
create policy "gestores consultam funil da empresa"
on public.store_analytics_events for select to authenticated
using (public.has_store_access(store_id));

-- O navegador nunca lê nem escreve credenciais diretamente. Somente Edge Functions
-- com a service role podem chamar estas funções e acessar o Vault.
create or replace function public.save_mercadopago_credentials(
  target_store_id uuid,
  p_access_token text,
  p_public_key text,
  p_webhook_secret text,
  p_account_id text,
  p_account_email text,
  p_live_mode boolean,
  p_enabled boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  old_access_id uuid;
  old_webhook_id uuid;
  next_access_id uuid;
  next_webhook_id uuid;
begin
  if nullif(trim(p_access_token), '') is null then
    raise exception 'Access Token obrigatório.';
  end if;

  select config.access_token_secret_id, config.webhook_secret_id
    into old_access_id, old_webhook_id
  from public.payment_provider_configs as config
  where config.store_id = target_store_id;

  next_access_id := vault.create_secret(
    trim(p_access_token),
    null,
    'Mercado Pago Access Token da empresa ' || target_store_id::text
  );

  if nullif(trim(coalesce(p_webhook_secret, '')), '') is not null then
    next_webhook_id := vault.create_secret(
      trim(p_webhook_secret),
      null,
      'Mercado Pago Webhook Secret da empresa ' || target_store_id::text
    );
  else
    next_webhook_id := old_webhook_id;
  end if;

  insert into public.payment_provider_configs (
    store_id, provider, enabled, public_key, access_token_secret_id,
    webhook_secret_id, account_id, account_email, live_mode, updated_at
  ) values (
    target_store_id, 'mercadopago', p_enabled, trim(coalesce(p_public_key, '')),
    next_access_id, next_webhook_id, trim(coalesce(p_account_id, '')),
    lower(trim(coalesce(p_account_email, ''))), p_live_mode, now()
  )
  on conflict (store_id) do update set
    provider = excluded.provider,
    enabled = excluded.enabled,
    public_key = excluded.public_key,
    access_token_secret_id = excluded.access_token_secret_id,
    webhook_secret_id = excluded.webhook_secret_id,
    account_id = excluded.account_id,
    account_email = excluded.account_email,
    live_mode = excluded.live_mode,
    updated_at = now();

  if old_access_id is not null and old_access_id <> next_access_id then
    delete from vault.secrets where id = old_access_id;
  end if;
  if old_webhook_id is not null and old_webhook_id <> next_webhook_id then
    delete from vault.secrets where id = old_webhook_id;
  end if;
end;
$$;

create or replace function public.get_payment_provider_secret(
  target_store_id uuid,
  requested_provider text default 'mercadopago'
)
returns table (
  access_token text,
  webhook_secret text,
  public_key text,
  enabled boolean,
  account_id text,
  account_email text,
  live_mode boolean,
  apple_pay_status text
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    access_secret.decrypted_secret,
    webhook_secret.decrypted_secret,
    config.public_key,
    config.enabled,
    config.account_id,
    config.account_email,
    config.live_mode,
    config.apple_pay_status
  from public.payment_provider_configs as config
  left join vault.decrypted_secrets as access_secret
    on access_secret.id = config.access_token_secret_id
  left join vault.decrypted_secrets as webhook_secret
    on webhook_secret.id = config.webhook_secret_id
  where config.store_id = target_store_id
    and config.provider = requested_provider
  limit 1;
$$;

create or replace function public.delete_payment_provider_credentials(target_store_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  access_id uuid;
  webhook_id uuid;
begin
  select config.access_token_secret_id, config.webhook_secret_id
    into access_id, webhook_id
  from public.payment_provider_configs as config
  where config.store_id = target_store_id;

  delete from public.payment_provider_configs where store_id = target_store_id;
  if access_id is not null then delete from vault.secrets where id = access_id; end if;
  if webhook_id is not null then delete from vault.secrets where id = webhook_id; end if;
end;
$$;

create or replace function public.platform_commerce_summary()
returns table (
  store_id uuid,
  orders bigint,
  paid_orders bigint,
  revenue numeric,
  customers bigint,
  begin_checkout bigint,
  payment_failures bigint
)
language sql
stable
security definer
set search_path = ''
as $$
  with order_totals as (
    select
      source.store_id,
      count(*)::bigint as orders,
      count(*) filter (where source.payment_status = 'pago')::bigint as paid_orders,
      coalesce(sum(source.total) filter (where source.payment_status = 'pago'), 0)::numeric as revenue,
      count(distinct coalesce(
        nullif('email:' || lower(trim(source.customer->>'email')), 'email:'),
        nullif('phone:' || regexp_replace(source.customer->>'phone', '\D', '', 'g'), 'phone:'),
        nullif('name:' || lower(trim(source.customer->>'name')), 'name:')
      ))::bigint as customers
    from public.orders as source
    where source.status <> 'cancelado'
    group by source.store_id
  ), event_totals as (
    select source.store_id,
      count(*) filter (where source.event_name = 'begin_checkout')::bigint as begin_checkout
    from public.store_analytics_events as source
    group by source.store_id
  ), failure_totals as (
    select source.store_id,
      count(*) filter (where source.status in ('rejected','error'))::bigint as payment_failures
    from public.payment_attempts as source
    group by source.store_id
  )
  select
    store.id,
    coalesce(order_totals.orders, 0),
    coalesce(order_totals.paid_orders, 0),
    coalesce(order_totals.revenue, 0),
    coalesce(order_totals.customers, 0),
    coalesce(event_totals.begin_checkout, 0),
    coalesce(failure_totals.payment_failures, 0)
  from public.stores as store
  left join order_totals on order_totals.store_id = store.id
  left join event_totals on event_totals.store_id = store.id
  left join failure_totals on failure_totals.store_id = store.id;
$$;

revoke all on function public.save_mercadopago_credentials(uuid,text,text,text,text,text,boolean,boolean) from public, anon, authenticated;
revoke all on function public.get_payment_provider_secret(uuid,text) from public, anon, authenticated;
revoke all on function public.delete_payment_provider_credentials(uuid) from public, anon, authenticated;
revoke all on function public.platform_commerce_summary() from public, anon, authenticated;
grant execute on function public.save_mercadopago_credentials(uuid,text,text,text,text,text,boolean,boolean) to service_role;
grant execute on function public.get_payment_provider_secret(uuid,text) to service_role;
grant execute on function public.delete_payment_provider_credentials(uuid) to service_role;
grant execute on function public.platform_commerce_summary() to service_role;

drop trigger if exists payment_provider_configs_touch_updated_at on public.payment_provider_configs;
create trigger payment_provider_configs_touch_updated_at
before update on public.payment_provider_configs
for each row execute function public.touch_updated_at();
